Repository omichel/test_world, pull requests merged in 2019-08, with the labels that each got.

#7 Cpp Controller Example
  examples_new/common/game.hpp
  examples_new/common/json.hpp
  examples_new/common/player.cpp
  examples_new/common/player.hpp
  examples_new/player_random-walk_cpp/.gitignore
  examples_new/player_random-walk_cpp/CMakeLists.txt
  examples_new/player_random-walk_cpp/player_random-walk.cpp
Labels: enhancement

#6 Fix support of commentator and reporter programs
  controllers/supervisor/constants.py
  controllers/supervisor/supervisor.py
  examples_new/commentator_skeleton_py/commentator_skeleton.py
  examples_new/commentator_skeleton_py/participant_base.py
  examples_new/common/__init__.py
  examples_new/common/participant.py
  examples_new/player_random-walk_py/player.py
  examples_new/player_random-walk_py/player_random-walk.py
  examples_new/player_rulebased-B_py/player.py
  examples_new/player_rulebased-B_py/player_rulebased-B.py
  examples_new/player_skeleton_py/player.py
  examples_new/player_skeleton_py/player_skeleton.py
  examples_new/reporter_skeleton_py/reporter_skeleton.py
Labels: bug, enhancement

#14 Fixed incomplete data read from socket
  controllers/supervisor/supervisor.py
Labels: bug

#15 Add an Image Fetcher Example
  controllers/supervisor/image_frame_buffer.py
  controllers/supervisor/supervisor.py
  examples_new/general_image-fetch_py/general_image-fetch.py
Labels: enhancement

#16 Fix initial performance
  controllers/supervisor/supervisor.py
Labels: bug

#17 Fixed end time and display
  controllers/supervisor/supervisor.py
Labels: bug

#22 Fixed Python shebang use for participants programs from supervisor.py
  controllers/supervisor/supervisor.py
  examples_new/commentator_skeleton_py/commentator_skeleton.py
  examples_new/general_image-fetch_py/general_image-fetch.py
  examples_new/player_random-walk_py/player_random-walk.py
  examples_new/player_rulebased-B_py/player_rulebased-B.py
  examples_new/player_skeleton_py/player_skeleton.py
  examples_new/reporter_skeleton_py/reporter_skeleton.py
Labels: bug

#24 Use OpenCV instead of PIL to show images.
  controllers/supervisor/image_frame_buffer.py
  examples_new/general_image-fetch_py/general_image-fetch.py
Labels: enhancement

#23 Fixed compilation of C++ controller on Windows
  examples_new/common/player.cpp
  examples_new/player_random-walk_cpp/.gitignore
  examples_new/player_random-walk_cpp/Makefile
Labels: bug

#25 Show camera image
  examples_new/general_image-fetch_py/general_image-fetch.py
Labels: enhancement

#26 Fix coordinates sent to Team B
  controllers/supervisor/supervisor.py
Labels: bug

#27 Fixed touch detection
  controllers/supervisor/supervisor.py
Labels: bug

#28 Fixed receipt of reporter's report by supervisor
  config.json
  controllers/supervisor/supervisor.py
  reports/.gitignore
  reports/PLACEHOLDER
Labels: bug

#29 Set the supervisor time step to 50 ms
  controllers/supervisor/supervisor.py
Labels: enhancement
